version: '3'
services:
  mysql:
    image: mysql:8.0.25
    container_name: fresher-mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode="" --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: '1'
      MYSQL_DATABASE: fresher
      MYSQL_USER: 'fresher'
      MYSQL_PASSWORD: '1'
      LANG: C.UTF-8
    ports:
      - 4306:3306
